FROM hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1

WORKDIR /app

COPY ../build.sbt ./
COPY ../project ./project

COPY ./tuiService/src/main/scala ./tuiService/src/main/scala

EXPOSE 8082

CMD ["sbt",  "tuiService/run"]