version: "3.8"

services:
  core:
    container_name: poker-core
    build:
      context: .          # Projekt‑Root
      dockerfile: Dockerfile
      target: core        # <-- Runtime‑Stage "core"
    ports:
      - "8080:8080"

  eval:
    container_name: poker-eval
    build:
      context: .
      dockerfile: Dockerfile
      target: eval        # <-- Stage "eval"
    ports:
      - "8083:8083"
    depends_on: [core]

  dbservice:
    container_name: poker-dbservice
    build:
      context: .
      dockerfile: Dockerfile
      target: db          # <-- Stage "db"
    ports:
      - "8084:8084"
    depends_on: [core]
