version: "3.8"

services:
  core:
    container_name: poker-core
    build:
      context: .
      dockerfile: coreService/Dockerfile
    stdin_open: true
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    environment:
      - POKER_CORE_PORT=8080

  eval:
    container_name: poker-eval
    build:
      context: .
      dockerfile: evalService/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - core
    environment:
      - POKER_EVAL_PORT=8083

  tui:
    container_name: poker-tui
    build:
      context: .
      dockerfile: tuiService/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - core
      - eval
    environment:
      - POKER_TUI_PORT=8082

  dbservice:
    container_name: poker-dbservice
    build:
      context: .
      dockerfile: dbService/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - core
    environment:
      - POKER_EVAL_PORT=8084
      

