version: "3.8"

services:
  core:
    container_name: poker-core
    build:
      context: .
      dockerfile: coreService/Dockerfile
    stdin_open: true
    env_file:
      - .env
    tty: true
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DB_POSTGRES_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - POKER_CORE_PORT=8080

  eval:
    container_name: poker-eval
    build:
      context: .
      dockerfile: evalService/Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      - core
    environment:
      - POKER_EVAL_PORT=8083

  tui:
    container_name: poker-tui
    build:
      context: .
      dockerfile: tuiService/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - core
      - eval
    environment:
      - POKER_TUI_PORT=8082

  dbservice:
    container_name: poker-dbservice
    build:
      context: .
      dockerfile: dbService/Dockerfile
    ports:
      - "8084:8084"
    depends_on:
      - core
    environment:
      - POKER_EVAL_PORT=8084
      - DATABASE_URL=postgresql://pokeruser:pokerpassword@db:5432/pokerdb  # Updated to connect to PostgreSQL

  db:
    container_name: poker-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"  # Exposing PostgreSQL port
    volumes:
      - poker-db-data:/var/lib/postgresql/data  # Ensuring data persistence with volumes

volumes:
  poker-db-data:  # Defining volume for persistent data storage
