FROM hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1

WORKDIR /app

COPY ../build.sbt ./
COPY ../project ./project

COPY ./dbService/src/main/scala ./dbService/src/main/scala

EXPOSE 8084

CMD ["sbt",  "dbService/run"]