FROM hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1

WORKDIR /app

COPY ../build.sbt ./
COPY ../project ./project

COPY ./evalService/src/main ./evalService/src/main

EXPOSE 8083

CMD ["sbt",  "evalService/run"]