FROM hseeberger/scala-sbt:17.0.2_1.6.2_3.1.1

WORKDIR /app

COPY ../build.sbt ./
COPY ../project ./project

COPY ./evalService/src/main/scala ./evalService/src/main/scala

EXPOSE 8083

CMD ["sbt",  "evalService/run"]