# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: ["main", "coveralls"]
  pull_request:
    branches: ["main", "coveralls"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"
      - name: Install sbt
        run: |
          curl -L -o sbt.deb https://github.com/sbt/sbt/releases/download/v1.9.8/sbt-1.9.8.deb
          sudo dpkg -i sbt.deb
          sudo apt-get update
          sudo apt-get install sbt
      - name: Run tests
        run: sbt test
      - name: Coveralls
        run: sbt clean coverage test coverageReport
      - name: Upload coveralls
        run: sbt coverageReport coveralls
