# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Scala CI

on:
  push:
    branches: ["main", "coveralls"]
  pull_request:
    branches: ["main", "coveralls"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: "sbt"
      - name: Run tests
        run: sbt 'testOnly de.htwg.poker.controller.ControllerSpec de.htwg.poker.model.CardsSpec de.htwg.poker.model.GameStateSpec de.htwg.poker.model.PlayerSpec de.htwg.poker.util.EvaluatorSpec de.htwg.poker.util.ObserverSpec de.htwg.poker.util.UndoSpec'
      - name: Coveralls
        run: sbt clean coverage test coverageReport
      - name: Upload coveralls
        run: sbt coverageReport coveralls
